# Force 100% solid color on Jellyfin Desktop client
windowrule = tag +standalone-media-apps, match:class (org\.jellyfin\.JellyfinDesktop|mpv|vlc)
windowrule = tag -default-opacity, match:tag standalone-media-apps

windowrule = opacity 1.0 override 1.0 override, match:tag standalone-media-apps
